version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - init-submodules:
          steps:
            - run: >-
                git submodule sync && 
                git submodule update --init

      - node/with-cache:
          steps:
            - run: >-
                cd server &&
                npm install &&
                echo "yeah"
workflows:
    build-only:
      jobs:
        - build