version: 2.1
orbs:
  node: circleci/node@3.0.1
  docker: circleci/docker@1.3.0
jobs:
  buildNodeApp:
    executor:
      name: node/default
    steps:
      - checkout
      - run: >-
          git submodule sync && 
          git submodule update --init
      - node/install-packages:
          app-dir: ./server
          pkg-manager: yarn
          override-ci-command: yarn install
      # - docker/build:
      #     image: valorad/xmjcraft
      # - docker/push:
      #     digest-path: /tmp/digest.txt
      #     image: valorad/xmjcraft
      #     tag: latest,v0.2.0
      # - run:
      #     command: |
      #       echo "Digest is: $(</tmp/digest.txt)"
workflows:
    mainPipe:
      jobs:
        - buildNodeApp
        - docker/publish:
            context: context0
            image: valorad/xmjcraft
            update-description: true