version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - run: >-
          git submodule sync && 
          git submodule update --init
      - node/install-packages:
          app-dir: ./server

workflows:
    build-only:
      jobs:
        - build